import 'src/styles/globals.css'
import Head from 'next/head'
import { useCounter } from "src/hooks/useCounter"
import { useInputArray } from "src/hooks/useInputArray"
import { useBgColor } from "src/hooks/useBgColor"

function MyApp({ Component, pageProps }) {
  const counter = useCounter() //  {count, isShow, handleClick, handleDisplay}
  const inputArray = useInputArray() //  {text, array, handleChange, handleAdd}
  useBgColor()

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} {...counter} {...inputArray} />
    </>
  )
}

export default MyApp
